### ISSUE TITLE
the process of dataset

### ISSUE THREAD

**Issue by arnold-em** [AaronHeee/RecFormer#1]
Traceback (most recent call last):
  File "D:\download\RecFormer-main\RecFormer-main\pretrain_data\meta_data_process.py", line 53, in <module>
    if line['asin'] is not None and line['title'] is not None:
KeyError: 'title'

(text) D:\download\RecFormer-main\RecFormer-main\pretrain_data>python meta_data_process.py
Check meta asins:  25%|███████████▊                                   | 2/8 [01:18<03:55, 39.31s/it]
Traceback (most recent call last):
  File "D:\download\RecFormer-main\RecFormer-main\pretrain_data\meta_data_process.py", line 53, in <module>
    if line['asin'] is not None and line['title'] is not None:
KeyError: 'title'
there have some trouble
may i ask why

**Comment by JiachengLi1995** [comment]
The key "title" is absent in the metadata of this item.
If your training data is the same as ours, you can directly download it from [here](https://drive.google.com/file/d/11wTD3jMoP_Fb5SlHfKr28NIMCnG_jOpy/view).
Otherwise, you can change this line of code to
`if line['asin'] is not None and 'title' in line and line['title'] is not None:`

**Comment by AaronHeee** [comment]
Closing the issue due to no recent activities.
